CREATE TABLE feeling (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  color TEXT
);

CREATE TYPE emotion_options AS ENUM (
  'Joy', 
  'Sadness', 
  'Anger',
  'Fear',
  'Anxiety',
  'Excitment',
  'Guilt',
  'Gratidude'
  );

ALTER TABLE feeling
ADD emotion emotion_options;

