CREATE TABLE pending (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  share_type share_types,
  audio_share TEXT, 
  text_share TEXT,
  feeling_id INTEGER REFERENCES feeling(id) ON DELETE CASCADE NOT NULL,
  emotion TEXT
  );

CREATE TABLE archive (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  share_type share_types,
  audio_share TEXT, 
  text_share TEXT,
  feeling_id INTEGER REFERENCES feeling(id) ON DELETE CASCADE NOT NULL,
  emotion TEXT
  );
